"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Sparkles, Send, RefreshCw, FileText, Plus, X, Save } from "lucide-react";
import { Card, Chip } from "@/components/ui";
import { AI_NAME } from "@/lib/ai-name";
import { draftEstimate, saveEstimateLines, saveEstimateNotes, sendEstimate } from "@/lib/actions/leads";

type Line = { label: string; value: string };
type Estimate = {
  status: "draft" | "sent";
  sentLabel: string;
  notes: string;
  lines: Line[];
  total: string;
} | null;

/** Rough-estimate tab: draft with the local model, hand-edit the line items +
 *  total, and email it to the lead. The on-page preview IS the house-style
 *  template PDF (rendered from the saved estimate), so what you see is what the
 *  client gets. Owner-gated server-side. */
export function LeadEstimate({
  slug,
  estimate,
  hasEmail,
}: {
  slug: string;
  estimate: Estimate;
  hasEmail: boolean;
}) {
  const router = useRouter();
  const [notes, setNotes] = useState(estimate?.notes ?? "");
  const [lines, setLines] = useState<Line[]>(estimate?.lines ?? []);
  const [total, setTotal] = useState(estimate?.total ?? "");
  const [previewVer, setPreviewVer] = useState(0);
  const [drafting, startDraft] = useTransition();
  const [saving, startSave] = useTransition();
  const [sending, startSend] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [sentOk, setSentOk] = useState(false);

  // Local edit state is seeded from props; the parent remounts this component
  // (via a `key` tied to the estimate) whenever the server estimate changes
  // — a re-draft or a save — so state re-seeds without a syncing effect.

  function draft() {
    setError(null);
    startDraft(async () => {
      const res = await draftEstimate(slug);
      if (!res.ok) setError(res.error ?? "Could not draft.");
      else router.refresh();
    });
  }

  async function persist() {
    const res = await saveEstimateLines(slug, lines, total);
    if (notes !== (estimate?.notes ?? "")) await saveEstimateNotes(slug, notes);
    return res;
  }

  function save() {
    setError(null);
    startSave(async () => {
      const res = await persist();
      if (res.ok) {
        setPreviewVer((v) => v + 1);
        router.refresh();
      } else setError(res.error ?? "Could not save.");
    });
  }

  function send() {
    setError(null);
    startSend(async () => {
      // Persist edits first so the emailed PDF matches what's on screen.
      const saved = await persist();
      if (!saved.ok) return setError(saved.error ?? "Could not save.");
      const res = await sendEstimate(slug);
      if (res.ok) setSentOk(true);
      else setError(res.error ?? "Could not send.");
    });
  }

  const setLine = (i: number, key: keyof Line, val: string) =>
    setLines((ls) => ls.map((l, j) => (j === i ? { ...l, [key]: val } : l)));
  const addLine = () => setLines((ls) => [...ls, { label: "", value: "" }]);
  const removeLine = (i: number) => setLines((ls) => ls.filter((_, j) => j !== i));

  const sent = estimate?.status === "sent" || sentOk;
  const busy = drafting || saving || sending;
  const inputCls =
    "w-full rounded-md border border-rule bg-card px-2 py-1 text-[12px] text-ink placeholder:text-ink-3 focus:border-accent focus:outline-none";

  if (!estimate) {
    return (
      <Card kind="dashed" className="max-w-[640px] p-8 text-center">
        <div className="font-serif text-[16px] font-semibold text-ink-2">No estimate yet</div>
        <div className="mt-1 text-[12px] text-ink-3">
          {AI_NAME} drafts a Phase 1 rough estimate from the scope + intake answers — then you can edit it.
        </div>
        <button
          type="button"
          onClick={draft}
          disabled={drafting}
          className="mt-4 inline-flex items-center gap-1.5 rounded-md border border-ai bg-ai px-3 py-1.5 text-[12px] font-semibold text-white hover:bg-ai-2 disabled:opacity-60"
        >
          <Sparkles className="size-3.5" strokeWidth={1.5} />
          {drafting ? `${AI_NAME} is drafting…` : `Draft with ${AI_NAME}`}
        </button>
        {error && <div className="mt-2 text-[11px] text-flag">{error}</div>}
      </Card>
    );
  }

  return (
    <Card className="max-w-[720px] p-3.5">
      <div className="flex items-center gap-2">
        <h3 className="flex-1 font-serif text-[16px] font-semibold text-ink">Phase 1 rough estimate</h3>
        <Chip kind="ai">Generated by {AI_NAME}</Chip>
        <Chip kind={sent ? "money" : "ghost"}>{sent ? estimate.sentLabel || "Sent" : "Draft"}</Chip>
      </div>

      {/* Steering notes */}
      <label className="mt-3 flex flex-col gap-1">
        <span className="font-mono text-[10px] uppercase tracking-[0.12em] text-ink-3">Notes to steer the estimate</span>
        <textarea
          value={notes}
          rows={2}
          placeholder="e.g. mid-tier finishes, keep the range tight — two competing bids."
          onChange={(e) => setNotes(e.target.value)}
          className="resize-y rounded-md border border-rule bg-paper px-2.5 py-1.5 text-[12px] text-ink-2 outline-none focus:border-accent"
        />
      </label>

      {/* Editable line items */}
      <div className="mt-3">
        <div className="mb-1 flex items-center justify-between">
          <span className="font-mono text-[10px] uppercase tracking-[0.12em] text-ink-3">Line items</span>
          <button type="button" onClick={addLine} className="inline-flex items-center gap-1 text-[11px] font-semibold text-accent-2 hover:underline">
            <Plus className="size-3" strokeWidth={2} /> Add line
          </button>
        </div>
        <div className="flex flex-col gap-1.5">
          {lines.map((line, i) => (
            <div key={i} className="flex items-center gap-2">
              <input
                value={line.label}
                onChange={(e) => setLine(i, "label", e.target.value)}
                placeholder="Item / description"
                className={`${inputCls} flex-1`}
              />
              <input
                value={line.value}
                onChange={(e) => setLine(i, "value", e.target.value)}
                placeholder="$ range or amount"
                className={`${inputCls} w-[190px] font-mono`}
              />
              <button
                type="button"
                onClick={() => removeLine(i)}
                aria-label="Remove line"
                className="flex-none rounded-md border border-rule bg-card p-1 text-ink-3 hover:bg-paper-2 hover:text-flag"
              >
                <X className="size-3" strokeWidth={2} />
              </button>
            </div>
          ))}
          {lines.length === 0 && (
            <div className="text-[11px] text-ink-3">No line items yet — add one, or re-draft with {AI_NAME}.</div>
          )}
        </div>
        <div className="mt-2 flex items-center gap-2 border-t-2 border-ink-2 pt-2">
          <span className="flex-1 font-serif text-[14px] font-semibold text-ink">Rough total</span>
          <input
            value={total}
            onChange={(e) => setTotal(e.target.value)}
            placeholder="e.g. $49.3k – $60.7k"
            className={`${inputCls} w-[190px] font-mono font-semibold text-accent-2`}
          />
        </div>
      </div>

      {error && <div className="mt-2 text-[11px] text-flag">{error}</div>}

      <div className="mt-3 flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={save}
          disabled={busy}
          className="inline-flex items-center gap-1.5 rounded-md border border-accent bg-accent px-2.5 py-1 text-[12px] font-semibold text-white hover:bg-accent-2 disabled:opacity-60"
        >
          <Save className="size-3" strokeWidth={1.75} />
          {saving ? "Saving…" : "Save & refresh preview"}
        </button>
        <button
          type="button"
          onClick={draft}
          disabled={busy}
          className="inline-flex items-center gap-1.5 rounded-md border border-rule bg-card px-2.5 py-1 text-[12px] font-semibold text-ink hover:bg-paper-2 disabled:opacity-60"
        >
          <RefreshCw className="size-3" strokeWidth={1.5} />
          {drafting ? "Re-drafting…" : `Re-draft with ${AI_NAME}`}
        </button>
        <a
          href={`/api/leads/${slug}/rough-estimate`}
          target="_blank"
          rel="noopener"
          className="inline-flex items-center gap-1.5 rounded-md border border-rule bg-card px-2.5 py-1 text-[12px] font-semibold text-ink hover:bg-paper-2"
        >
          <FileText className="size-3" strokeWidth={1.5} />
          Open PDF
        </a>
        <button
          type="button"
          onClick={send}
          disabled={busy || sent || !hasEmail}
          title={!hasEmail ? "Add an email to this lead first" : undefined}
          className="ml-auto inline-flex items-center gap-1.5 rounded-md border border-ink bg-ink px-2.5 py-1 text-[12px] font-semibold text-paper hover:bg-[#232a1e] disabled:opacity-50"
        >
          <Send className="size-3" strokeWidth={1.5} />
          {sent ? "Sent ✓" : sending ? "Sending…" : "Email to lead"}
        </button>
      </div>

      {/* Client preview — the actual house-style template PDF, rendered from the
          saved estimate. Save to refresh it after edits. */}
      <div className="mt-4">
        <div className="mb-1 font-mono text-[10px] uppercase tracking-[0.12em] text-ink-3">
          Client preview · house-style PDF (attached when you email)
        </div>
        <iframe
          key={previewVer}
          src={`/api/leads/${slug}/rough-estimate?v=${previewVer}`}
          title="Rough estimate preview"
          className="h-[560px] w-full rounded-md border border-rule bg-paper"
        />
      </div>
    </Card>
  );
}
