"use client";

import { useState, useTransition } from "react";
import { Sparkles, Send, RefreshCw } from "lucide-react";
import { Card, Chip } from "@/components/ui";
import { AI_NAME } from "@/lib/ai-name";
import { draftEstimate, saveEstimateNotes, sendEstimate } from "@/lib/actions/leads";

type Estimate = {
  status: "draft" | "sent";
  sentLabel: string;
  notes: string;
  lines: { label: string; value: string }[];
  total: string;
} | null;

/** Rough-estimate tab: draft with the local model, edit steering notes, and
 *  email it to the lead. Owner-gated server-side; optimistic client state. */
export function LeadEstimate({
  slug,
  estimate,
  hasEmail,
}: {
  slug: string;
  estimate: Estimate;
  hasEmail: boolean;
}) {
  const [notes, setNotes] = useState(estimate?.notes ?? "");
  const [drafting, startDraft] = useTransition();
  const [sending, startSend] = useTransition();
  const [error, setError] = useState<string | null>(null);
  const [sentOk, setSentOk] = useState(false);

  function draft() {
    setError(null);
    startDraft(async () => {
      const res = await draftEstimate(slug);
      if (!res.ok) setError(res.error ?? "Could not draft.");
    });
  }

  function send() {
    setError(null);
    startSend(async () => {
      // Persist any edited notes first so they're on record with the sent estimate.
      if (notes !== (estimate?.notes ?? "")) await saveEstimateNotes(slug, notes);
      const res = await sendEstimate(slug);
      if (res.ok) setSentOk(true);
      else setError(res.error ?? "Could not send.");
    });
  }

  const sent = estimate?.status === "sent" || sentOk;

  if (!estimate) {
    return (
      <Card kind="dashed" className="max-w-[640px] p-8 text-center">
        <div className="font-serif text-[16px] font-semibold text-ink-2">No estimate yet</div>
        <div className="mt-1 text-[12px] text-ink-3">
          {AI_NAME} drafts a Phase 1 rough estimate from the scope + intake answers.
        </div>
        <button
          type="button"
          onClick={draft}
          disabled={drafting}
          className="mt-4 inline-flex items-center gap-1.5 rounded-md border border-ai bg-ai px-3 py-1.5 text-[12px] font-semibold text-white hover:bg-ai-2 disabled:opacity-60"
        >
          <Sparkles className="size-3.5" strokeWidth={1.5} />
          {drafting ? `${AI_NAME} is drafting…` : `Draft with ${AI_NAME}`}
        </button>
        {error && <div className="mt-2 text-[11px] text-flag">{error}</div>}
      </Card>
    );
  }

  return (
    <Card className="max-w-[640px] p-3.5">
      <div className="flex items-center gap-2">
        <h3 className="flex-1 font-serif text-[16px] font-semibold text-ink">
          Phase 1 rough estimate
        </h3>
        <Chip kind="ai">Generated by {AI_NAME}</Chip>
        <Chip kind={sent ? "money" : "ghost"}>{sent ? estimate.sentLabel || "Sent" : "Draft"}</Chip>
      </div>

      {/* Steering notes */}
      <label className="mt-3 flex flex-col gap-1">
        <span className="font-mono text-[10px] uppercase tracking-[0.12em] text-ink-3">
          Notes to steer the estimate
        </span>
        <textarea
          value={notes}
          rows={2}
          placeholder="e.g. mid-tier finishes, keep the range tight — two competing bids."
          onChange={(e) => setNotes(e.target.value)}
          onBlur={() => {
            if (notes !== (estimate.notes ?? "")) saveEstimateNotes(slug, notes);
          }}
          className="resize-y rounded-md border border-rule bg-paper px-2.5 py-1.5 text-[12px] text-ink-2 outline-none focus:border-accent"
        />
      </label>

      {/* Line items */}
      <div className="mt-3 flex flex-col">
        {estimate.lines.map((line, i) => (
          <div
            key={line.label}
            className={`flex items-center py-1 ${i ? "border-t border-dashed border-rule-soft" : ""}`}
          >
            <span className="flex-1 text-[13px] text-ink-2">{line.label}</span>
            <span className="font-mono text-[12px] text-ink-2">{line.value}</span>
          </div>
        ))}
        <div className="mt-1.5 flex items-center border-t-2 border-ink-2 pt-2">
          <span className="flex-1 font-serif text-[16px] font-semibold text-ink">Rough total</span>
          <span className="font-mono text-[16px] font-semibold text-accent-2">{estimate.total}</span>
        </div>
      </div>

      {error && <div className="mt-2 text-[11px] text-flag">{error}</div>}

      <div className="mt-3 flex items-center gap-2">
        <button
          type="button"
          onClick={draft}
          disabled={drafting || sending}
          className="inline-flex items-center gap-1.5 rounded-md border border-rule bg-card px-2.5 py-1 text-[12px] font-semibold text-ink hover:bg-paper-2 disabled:opacity-60"
        >
          <RefreshCw className="size-3" strokeWidth={1.5} />
          {drafting ? "Re-drafting…" : "Re-draft"}
        </button>
        <button
          type="button"
          onClick={send}
          disabled={sending || drafting || sent || !hasEmail}
          title={!hasEmail ? "Add an email to this lead first" : undefined}
          className="inline-flex items-center gap-1.5 rounded-md border border-ink bg-ink px-2.5 py-1 text-[12px] font-semibold text-paper hover:bg-[#232a1e] disabled:opacity-50"
        >
          <Send className="size-3" strokeWidth={1.5} />
          {sent ? "Sent ✓" : sending ? "Sending…" : "Email to lead"}
        </button>
      </div>
    </Card>
  );
}
