import type { ReactNode } from "react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Sparkles, FileText } from "lucide-react";
import { Shell } from "@/components/shell/Shell";
import { Card, Chip, Avatar, Eyebrow } from "@/components/ui";
import { LeadTabs } from "@/components/leads/LeadTabs";
import { getLead, STAGES, stageIndex, stageLabel } from "@/lib/leads";
import { getLeadScore } from "@/lib/intake";
import { leadContext } from "@/lib/page-context";
import { getLeadActivity, type LeadActivityKind } from "@/lib/lead-activity";
import { advanceLeadStage, convertLeadToProject } from "@/lib/actions/leads";
import { DeleteLeadButton } from "@/components/leads/DeleteLeadButton";
import { LeadContact } from "@/components/leads/LeadContact";
import { ThankReferrerButton } from "@/components/leads/ThankReferrerButton";
import { LeadPhotos } from "@/components/leads/LeadPhotos";
import { LeadIntake } from "@/components/leads/LeadIntake";
import { LeadScore } from "@/components/leads/LeadScore";
import { LeadTasks } from "@/components/leads/LeadTasks";
import { getLeadTasks } from "@/lib/lead-tasks";
import { LeadEstimate } from "@/components/leads/LeadEstimate";
import { AI_NAME } from "@/lib/ai-name";

export default async function LeadDetailPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const lead = await getLead(slug);
  if (!lead) notFound();

  const activity = await getLeadActivity(slug);
  const score = await getLeadScore(slug);
  const tasks = await getLeadTasks(slug);

  const currentStageIdx = stageIndex(lead.stage);
  const nextStage = STAGES[currentStageIdx + 1];

  async function moveToNextStage() {
    "use server";
    await advanceLeadStage(slug);
  }

  async function convertToProject() {
    "use server";
    await convertLeadToProject(slug);
  }

  const overview = (
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-[1fr_320px]">
      {/* Main column */}
      <div className="flex flex-col gap-3.5">
        <LeadScore slug={lead.slug} initial={score} />

        <LeadIntake slug={lead.slug} items={lead.intake} />

        {lead.estimate && (
          <Card className="p-3.5">
            <div className="flex items-center gap-2">
              <h3 className="flex-1 font-serif text-[16px] font-semibold text-ink">
                Phase 1 rough estimate
              </h3>
              <Chip kind="ai">Generated by {AI_NAME}</Chip>
              <Chip kind="ghost">{lead.estimate.sentLabel}</Chip>
            </div>
            <div className="mt-2.5 flex flex-col">
              {lead.estimate.lines.map((line, i) => (
                <div
                  key={line.label}
                  className={`flex items-center py-1 ${i ? "border-t border-dashed border-rule-soft" : ""}`}
                >
                  <span className="flex-1 text-[13px] text-ink-2">{line.label}</span>
                  <span className="font-mono text-[12px] text-ink-2">{line.value}</span>
                </div>
              ))}
              <div className="mt-1.5 flex items-center border-t-2 border-ink-2 pt-2">
                <span className="flex-1 font-serif text-[16px] font-semibold text-ink">
                  Rough total
                </span>
                <span className="font-mono text-[16px] font-semibold text-accent-2">
                  {lead.estimate.total}
                </span>
              </div>
            </div>
          </Card>
        )}
      </div>

      {/* Sidebar */}
      <div className="flex flex-col gap-3">
        <Card kind="tan" className="p-3">
          <Eyebrow muted>Pipeline stage</Eyebrow>
          <div className="mt-2 flex flex-col gap-1.5">
            {STAGES.map((s, i) => {
              const done = i < currentStageIdx;
              const current = i === currentStageIdx;
              return (
                <div key={s.key} className="flex items-center gap-2">
                  <span
                    className={[
                      "size-3.5 flex-none rounded-[3px] border",
                      current
                        ? "border-accent bg-accent"
                        : done
                          ? "border-accent-2 bg-accent-2"
                          : "border-ink-4",
                    ].join(" ")}
                  />
                  <span className="w-3 font-mono text-[9px] text-ink-3">{i + 1}</span>
                  <span className={`flex-1 text-[13px] ${done || current ? "text-ink" : "text-ink-3"}`}>
                    {s.label}
                  </span>
                  {current && <Chip kind="accent">Here</Chip>}
                </div>
              );
            })}
          </div>
        </Card>

        <Card className="p-3">
          <Eyebrow muted>Cadence · SLA</Eyebrow>
          <div className="mt-2 flex flex-col gap-2">
            {lead.cadence.map((c) => (
              <div key={c.label} className="flex items-center gap-2">
                <span className="flex-1 text-[12px] text-ink-2">{c.label}</span>
                {c.chip ? (
                  <Chip kind={c.chip}>{c.value}</Chip>
                ) : (
                  <span className="font-mono text-[11px] text-ink-3">{c.value}</span>
                )}
              </div>
            ))}
          </div>
        </Card>

        <ThankReferrerButton
          slug={lead.slug}
          referrerName={lead.referrerName}
          referrerEmail={lead.referrerEmail}
          thanked={lead.referrerThanked}
        />

        <LeadPhotos slug={lead.slug} photos={lead.photos} placeholderCount={lead.photosCount} />
      </div>
    </div>
  );

  // ── Rough estimate panel — draft with the model + email to the lead ─────────
  const estimatePanel = (
    <LeadEstimate slug={lead.slug} estimate={lead.estimate} hasEmail={!!lead.email} />
  );

  // ── empty-state helper for tabs with no data yet ───────────────────────────
  const emptyPanel = (label: string, hint: string) => (
    <Card kind="dashed" className="max-w-[640px] p-8 text-center">
      <div className="font-serif text-[16px] font-semibold text-ink-2">{label}</div>
      <div className="mt-1 text-[12px] text-ink-3">{hint}</div>
    </Card>
  );

  // ── Activity panel — real lead_activity timeline (newest first) ─────────────
  const ACTIVITY_DOT: Record<LeadActivityKind, string> = {
    created: "bg-ink-4",
    stage: "bg-accent",
    estimate: "bg-ai",
    email: "bg-accent-2",
    contact: "bg-ink-3",
    note: "bg-ink-4",
  };
  const activityPanel =
    activity.length > 0 ? (
      <Card className="max-w-[640px] overflow-hidden p-0">
        <div className="border-b border-rule bg-paper-2 px-4 py-2.5 font-mono text-[10px] uppercase tracking-[0.14em] text-ink-3">
          Activity · {lead.ageDays}d since first contact
        </div>
        {activity.map((a, i) => (
          <div
            key={a.id}
            className={`flex items-start gap-3 px-4 py-2.5 ${i ? "border-t border-rule-soft" : ""}`}
          >
            <span className={`mt-1.5 size-2 flex-none rounded-full ${ACTIVITY_DOT[a.kind]}`} />
            <div className="min-w-0 flex-1">
              <div className="text-[13px] text-ink">{a.summary}</div>
              <div className="font-mono text-[10px] text-ink-3">
                {a.actor} · {a.when}
              </div>
            </div>
            {a.kind === "estimate" && <Chip kind="ai">{AI_NAME}</Chip>}
          </div>
        ))}
      </Card>
    ) : (
      emptyPanel("Activity", "Stage moves, estimates, and emails are logged here as they happen.")
    );

  // ── Conversation panel — full message thread ───────────────────────────────
  const conversationPanel =
    lead.conversation.length > 0 ? (
      <Card className="max-w-[640px] overflow-hidden p-0">
        {lead.conversation.map((msg, i) => (
          <div
            key={i}
            className={`px-4 py-3 ${i ? "border-t border-rule-soft" : ""} ${msg.role === "ai" ? "bg-ai-soft" : ""}`}
          >
            <div className="flex items-center gap-2">
              <span className="font-serif text-[13px] font-semibold text-ink">{msg.from}</span>
              {msg.role === "ai" && <Chip kind="ai">AI</Chip>}
              {msg.role === "you" && <Chip kind="ghost">You</Chip>}
              <span className="ml-auto font-mono text-[10px] text-ink-3">{msg.time}</span>
            </div>
            <p className="mt-1 text-[13px] text-ink-2">{msg.body}</p>
          </div>
        ))}
      </Card>
    ) : (
      emptyPanel("Conversation", "Messages with this lead land here once email + SMS are connected.")
    );

  // ── Files panel — lead-scoped documents ────────────────────────────────────
  const filesPanel =
    lead.files.length > 0 ? (
      <Card className="max-w-[640px] overflow-hidden p-0">
        {lead.files.map((f, i) => (
          <div
            key={f.name}
            className={`flex items-center gap-3 px-4 py-3 ${i ? "border-t border-rule-soft" : ""}`}
          >
            <FileText className="size-4 flex-none text-ink-3" strokeWidth={1.5} />
            <div className="min-w-0 flex-1">
              <div className="truncate text-[13px] text-ink">{f.name}</div>
              <div className="font-mono text-[10px] text-ink-3">{f.meta}</div>
            </div>
            {f.tag && <Chip kind="ai">{f.tag}</Chip>}
          </div>
        ))}
      </Card>
    ) : (
      emptyPanel("Files", "Photos, measurements, and estimates attached to this lead show up here.")
    );

  const panels: Record<string, ReactNode> = {
    Overview: overview,
    Tasks: <LeadTasks slug={lead.slug} tasks={tasks} />,
    Conversation: conversationPanel,
    "Rough estimate": estimatePanel,
    Files: filesPanel,
    Activity: activityPanel,
  };

  return (
    <Shell breadcrumb={`LEADS › ${lead.name.toUpperCase()}`} aiContext={leadContext(lead)}>
      <div className="mx-auto max-w-[1100px] px-7 py-6">
        <Link href="/leads" className="text-[11px] text-ink-3 hover:text-ink-2">
          ← All leads
        </Link>

        {/* Header */}
        <div className="mt-2 flex flex-wrap items-start gap-4">
          <Avatar initials={lead.initials} kind="accent" size="lg" />
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-1.5">
              <Chip kind="ghost">Source: {lead.source}</Chip>
              <Chip kind="ghost">
                Stage {currentStageIdx + 1} of {STAGES.length}
              </Chip>
            </div>
            <h1 className="mt-1.5 font-serif text-[30px] font-medium leading-none tracking-tight text-accent-2">
              {lead.name}
            </h1>
            <div className="mt-1.5 text-[11px] text-ink-3">{lead.address} · {lead.loggedLabel}</div>
          </div>
          <div className="flex items-center gap-1.5">
            <LeadContact slug={lead.slug} name={lead.name} phone={lead.phone} email={lead.email} />
            <Link
              href="/ai"
              className="inline-flex items-center gap-1 rounded-md border border-ai bg-ai px-2.5 py-1 text-[12px] font-semibold text-white hover:bg-ai-2"
            >
              <Sparkles className="size-3" strokeWidth={1.5} />
              Ask {AI_NAME}
            </Link>
            {lead.projectSlug ? (
              <Link
                href={`/projects/${lead.projectSlug}`}
                className="rounded-md border border-accent-2 bg-paper-2 px-2.5 py-1 text-[12px] font-semibold text-accent-2 hover:bg-accent-soft"
              >
                View project →
              </Link>
            ) : nextStage ? (
              <form action={moveToNextStage}>
                <button
                  type="submit"
                  className="rounded-md border border-ink bg-ink px-2.5 py-1 text-[12px] font-semibold text-paper hover:bg-[#232a1e]"
                >
                  Move to {nextStage.label}
                </button>
              </form>
            ) : (
              <form action={convertToProject}>
                <button
                  type="submit"
                  className="rounded-md border border-accent bg-accent px-2.5 py-1 text-[12px] font-semibold text-white hover:bg-accent-2"
                >
                  Convert to project
                </button>
              </form>
            )}
            <DeleteLeadButton slug={slug} name={lead.name} />
          </div>
        </div>

        <LeadTabs panels={panels} />
      </div>
    </Shell>
  );
}
