import type { ReactNode } from "react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Shell } from "@/components/shell/Shell";
import { Card, Chip, Eyebrow } from "@/components/ui";
import { CommandBar } from "@/components/cmdk/CommandBar";
import { LeadTabs } from "@/components/leads/LeadTabs";
import { getLead, STAGES, stageIndex, suggestedProjectName } from "@/lib/leads";
import { getLeadScore } from "@/lib/intake";
import { leadContext } from "@/lib/page-context";
import { getLeadActivity, type LeadActivityKind } from "@/lib/lead-activity";
import { advanceLeadStage, markLeadLost, reopenLead } from "@/lib/actions/leads";
import { DeleteLeadButton } from "@/components/leads/DeleteLeadButton";
import { ConvertLeadButton } from "@/components/leads/ConvertLeadButton";
import { LeadContact } from "@/components/leads/LeadContact";
import { ThankReferrerButton } from "@/components/leads/ThankReferrerButton";
import { LeadPhotos } from "@/components/leads/LeadPhotos";
import { LeadIntake } from "@/components/leads/LeadIntake";
import { LeadScore } from "@/components/leads/LeadScore";
import { LeadTasks } from "@/components/leads/LeadTasks";
import { getLeadTasks } from "@/lib/lead-tasks";
import { LeadEstimate } from "@/components/leads/LeadEstimate";
import { DocTypePanel } from "@/components/projects/DocTypePanel";
import { ProjectFiles } from "@/components/projects/ProjectFiles";
import { ProjectComms } from "@/components/projects/ProjectComms";
import { PortalAccessPanel, type PortalInviteSummary } from "@/components/portal/PortalAccessPanel";
import { listDocDrafts, listDocTemplates } from "@/lib/doc-drafts";
import { getLeadFiles } from "@/lib/projects";
import { getClientInvite } from "@/lib/client-invites";
import { getPortalThread, portalChannel } from "@/lib/portal-messages";
import { AI_NAME } from "@/lib/ai-name";
import { RecordOps } from "@/components/engine/RecordOps";
import { getRecordOps } from "@/lib/record-ops";
import { SendPreconButton } from "@/components/leads/SendPreconButton";

export default async function LeadDetailPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const lead = await getLead(slug);
  if (!lead) notFound();

  const activity = await getLeadActivity(slug);
  const score = await getLeadScore(slug);
  const tasks = await getLeadTasks(slug);
  const leadDocDrafts = await listDocDrafts({ leadSlug: slug });
  // rough_estimate has its own dedicated tab (LeadEstimate, backed by the
  // lead_estimates singleton, not document_drafts) — excluded here so it's not
  // duplicated as an always-visible, effectively-unused panel.
  const leadDocTemplates = listDocTemplates().filter(
    (t) => (t.scope === "both" || t.scope === "lead") && t.key !== "rough_estimate",
  );
  // Open Engine + Brain data scoped to this one lead — the "Ops" tab.
  const ops = await getRecordOps("lead", slug);

  // Client portal state for this lead: real uploaded files (with dashboard
  // share toggles), the invite, and the portal chat thread.
  const [leadFiles, invite, portalThread] = await Promise.all([
    getLeadFiles(slug),
    getClientInvite({ lead: slug }),
    getPortalThread(portalChannel("client", `lead:${slug}`)),
  ]);
  const inviteSummary: PortalInviteSummary = invite
    ? {
        status:
          invite.status === "dismissed"
            ? "dismissed"
            : invite.expiresAt < new Date()
              ? "expired"
              : "active",
        toEmail: invite.toEmail,
        expiresLabel: invite.expiresAt.toLocaleDateString("en-US", {
          month: "short",
          day: "numeric",
          year: "numeric",
        }),
        used: invite.usedAt !== null,
      }
    : { status: "none", toEmail: lead.email || null, expiresLabel: null, used: false };

  const isLost = lead.stage === "lost";
  const currentStageIdx = stageIndex(lead.stage);
  const nextStage = STAGES[currentStageIdx + 1];

  async function moveToNextStage() {
    "use server";
    await advanceLeadStage(slug);
  }

  async function markLost() {
    "use server";
    await markLeadLost(slug);
  }

  async function reopen() {
    "use server";
    await reopenLead(slug);
  }

  const overview = (
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-[1fr_320px]">
      {/* Main column */}
      <div className="flex flex-col gap-3.5">
        <LeadScore slug={lead.slug} initial={score} />

        <LeadIntake slug={lead.slug} items={lead.intake} />

        {lead.estimate && (
          <Card className="p-3.5">
            <div className="flex items-center gap-2">
              <h3 className="flex-1 font-serif text-[16px] font-semibold text-ink">
                Phase 1 rough estimate
              </h3>
              <Chip kind="ai">Generated by {AI_NAME}</Chip>
              <Chip kind="ghost">{lead.estimate.sentLabel}</Chip>
            </div>
            <div className="mt-2.5 flex flex-col">
              {lead.estimate.lines.map((line, i) => (
                <div
                  key={line.label}
                  className={`flex items-start justify-between gap-4 py-1 ${i ? "border-t border-dashed border-rule-soft" : ""}`}
                >
                  <span className="min-w-0 break-words text-[13px] text-ink-2">{line.label}</span>
                  <span className="min-w-0 break-words text-right font-mono text-[12px] text-ink-2">{line.value}</span>
                </div>
              ))}
              <div className="mt-1.5 flex items-start justify-between gap-4 border-t-2 border-ink-2 pt-2">
                <span className="min-w-0 break-words font-serif text-[16px] font-semibold text-ink">
                  Rough total
                </span>
                <span className="min-w-0 break-words text-right font-mono text-[16px] font-semibold text-accent-2">
                  {lead.estimate.total}
                </span>
              </div>
            </div>
          </Card>
        )}
      </div>

      {/* Sidebar */}
      <div className="flex flex-col gap-3">
        <Card kind="tan" className="p-3">
          <Eyebrow muted>Pipeline stage</Eyebrow>
          {isLost ? (
            <div className="mt-2 text-[13px] text-ink-2">
              This lead is <span className="font-semibold text-flag">lost / archived</span> — off the
              active pipeline. Reopen it to move it back to Intake.
            </div>
          ) : (
          <div className="mt-2 flex flex-col gap-1.5">
            {STAGES.map((s, i) => {
              const done = i < currentStageIdx;
              const current = i === currentStageIdx;
              return (
                <div key={s.key} className="flex items-center gap-2">
                  <span
                    className={[
                      "size-3.5 flex-none rounded-[3px] border",
                      current
                        ? "border-accent bg-accent"
                        : done
                          ? "border-accent-2 bg-accent-2"
                          : "border-ink-4",
                    ].join(" ")}
                  />
                  <span className="w-3 font-mono text-[9px] text-ink-3">{i + 1}</span>
                  <span className={`flex-1 text-[13px] ${done || current ? "text-ink" : "text-ink-3"}`}>
                    {s.label}
                  </span>
                  {current && <Chip kind="accent">Here</Chip>}
                </div>
              );
            })}
          </div>
          )}
          {!isLost && currentStageIdx >= stageIndex("rough_estimate") && <SendPreconButton />}
        </Card>

        <Card className="p-3">
          <Eyebrow muted>Cadence · SLA</Eyebrow>
          <div className="mt-2 flex flex-col gap-2">
            {lead.cadence.map((c) => (
              <div key={c.label} className="flex items-center gap-2">
                <span className="flex-1 text-[12px] text-ink-2">{c.label}</span>
                {c.chip ? (
                  <Chip kind={c.chip}>{c.value}</Chip>
                ) : (
                  <span className="font-mono text-[11px] text-ink-3">{c.value}</span>
                )}
              </div>
            ))}
          </div>
        </Card>

        <ThankReferrerButton
          slug={lead.slug}
          referrerName={lead.referrerName}
          referrerEmail={lead.referrerEmail}
          thanked={lead.referrerThanked}
        />

        <LeadPhotos slug={lead.slug} photos={lead.photos} placeholderCount={lead.photosCount} />
      </div>
    </div>
  );

  // ── Rough estimate panel — draft with the model + email to the lead ─────────
  const estimatePanel = (
    <LeadEstimate
      key={JSON.stringify(lead.estimate?.lines) + (lead.estimate?.total ?? "")}
      slug={lead.slug}
      estimate={lead.estimate}
      hasEmail={!!lead.email}
    />
  );

  // ── empty-state helper for tabs with no data yet ───────────────────────────
  const emptyPanel = (label: string, hint: string) => (
    <Card kind="dashed" className="max-w-[640px] p-8 text-center">
      <div className="font-serif text-[16px] font-semibold text-ink-2">{label}</div>
      <div className="mt-1 text-[12px] text-ink-3">{hint}</div>
    </Card>
  );

  // ── Activity panel — real lead_activity timeline (newest first) ─────────────
  const ACTIVITY_DOT: Record<LeadActivityKind, string> = {
    created: "bg-ink-4",
    stage: "bg-accent",
    estimate: "bg-ai",
    email: "bg-accent-2",
    contact: "bg-ink-3",
    note: "bg-ink-4",
  };
  const activityPanel =
    activity.length > 0 ? (
      <Card className="max-w-[640px] overflow-hidden p-0">
        <div className="border-b border-rule bg-paper-2 px-4 py-2.5 font-mono text-[10px] uppercase tracking-[0.14em] text-ink-3">
          Activity · {lead.ageDays}d since first contact
        </div>
        {activity.map((a, i) => (
          <div
            key={a.id}
            className={`flex items-start gap-3 px-4 py-2.5 ${i ? "border-t border-rule-soft" : ""}`}
          >
            <span className={`mt-1.5 size-2 flex-none rounded-full ${ACTIVITY_DOT[a.kind]}`} />
            <div className="min-w-0 flex-1">
              <div className="text-[13px] text-ink">{a.summary}</div>
              <div className="font-mono text-[10px] text-ink-3">
                {a.actor} · {a.when}
              </div>
            </div>
            {a.kind === "estimate" && <Chip kind="ai">{AI_NAME}</Chip>}
          </div>
        ))}
      </Card>
    ) : (
      emptyPanel("Activity", "Stage moves, estimates, and emails are logged here as they happen.")
    );

  // ── Conversation panel — full message thread ───────────────────────────────
  const conversationPanel =
    lead.conversation.length > 0 ? (
      <Card className="max-w-[640px] overflow-hidden p-0">
        {lead.conversation.map((msg, i) => (
          <div
            key={i}
            className={`px-4 py-3 ${i ? "border-t border-rule-soft" : ""} ${msg.role === "ai" ? "bg-ai-soft" : ""}`}
          >
            <div className="flex items-center gap-2">
              <span className="font-serif text-[13px] font-semibold text-ink">{msg.from}</span>
              {msg.role === "ai" && <Chip kind="ai">AI</Chip>}
              {msg.role === "you" && <Chip kind="ghost">You</Chip>}
              <span className="ml-auto font-mono text-[10px] text-ink-3">{msg.time}</span>
            </div>
            <p className="mt-1 text-[13px] text-ink-2">{msg.body}</p>
          </div>
        ))}
      </Card>
    ) : (
      emptyPanel("Conversation", "Messages with this lead land here once email + SMS are connected.")
    );

  // ── Files panel — REAL lead files (upload + dashboard share toggles), with
  // the old curated names kept below as a muted reference index. ─────────────
  const filesPanel = (
    <ProjectFiles leadSlug={lead.slug} files={leadFiles} showcase={lead.files.map((f) => f.name)} />
  );

  // ── Client portal panel — access link management + the portal chat thread ──
  const portalPanel = (
    <div className="max-w-[680px] space-y-4">
      <PortalAccessPanel scope={{ lead: lead.slug }} invite={inviteSummary} />
      <ProjectComms leadSlug={lead.slug} thread={portalThread} />
    </div>
  );

  const panels: Record<string, ReactNode> = {
    Overview: overview,
    Ops: ops ? <RecordOps ops={ops} /> : null,
    Tasks: <LeadTasks slug={lead.slug} tasks={tasks} />,
    Conversation: conversationPanel,
    "Rough estimate": estimatePanel,
    Documents: (
      <div className="space-y-8">
        {leadDocTemplates.map((t) => (
          <DocTypePanel
            key={t.key}
            leadSlug={lead.slug}
            templateKey={t.key}
            manifest={t}
            drafts={leadDocDrafts.filter((d) => d.template_key === t.key)}
          />
        ))}
      </div>
    ),
    Files: filesPanel,
    "Client portal": portalPanel,
    Activity: activityPanel,
  };

  return (
    <Shell breadcrumb={`LEADS › ${lead.name.toUpperCase()}`} aiContext={leadContext(lead)} embeddedAsk>
      <div className="mx-auto max-w-[1100px] px-7 py-6">
        <Link href="/leads" className="text-[11px] text-ink-3 hover:text-ink-2">
          ← All leads
        </Link>

        <div className="mt-3">
          <CommandBar embedded aiContext={leadContext(lead)} agents={["claude", "hermes"]} />
        </div>

        {/* Header */}
        <div className="mt-2 flex flex-wrap items-start gap-4">
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-1.5">
              <Chip kind="ghost">Source: {lead.source}</Chip>
              {isLost ? (
                <Chip kind="flag">Lost / Archived</Chip>
              ) : (
                <Chip kind="ghost">
                  Stage {currentStageIdx + 1} of {STAGES.length}
                </Chip>
              )}
            </div>
            <h1 className="mt-1.5 font-serif text-[30px] font-medium leading-none tracking-tight text-accent-2">
              {lead.name}
            </h1>
            <div className="mt-1.5 text-[11px] text-ink-3">{lead.address} · {lead.loggedLabel}</div>
          </div>
          <div className="flex items-center gap-1.5">
            <LeadContact slug={lead.slug} name={lead.name} phone={lead.phone} email={lead.email} />
            {lead.projectSlug ? (
              <Link
                href={`/projects/${lead.projectSlug}`}
                className="rounded-md border border-accent-2 bg-paper-2 px-2.5 py-1 text-[12px] font-semibold text-accent-2 hover:bg-accent-soft"
              >
                View project →
              </Link>
            ) : isLost ? (
              <form action={reopen}>
                <button
                  type="submit"
                  className="rounded-md border border-ink bg-ink px-2.5 py-1 text-[12px] font-semibold text-paper hover:bg-[#232a1e]"
                >
                  Reopen lead
                </button>
              </form>
            ) : nextStage ? (
              <form action={moveToNextStage}>
                <button
                  type="submit"
                  className="rounded-md border border-ink bg-ink px-2.5 py-1 text-[12px] font-semibold text-paper hover:bg-[#232a1e]"
                >
                  Move to {nextStage.label}
                </button>
              </form>
            ) : (
              <ConvertLeadButton
                slug={lead.slug}
                suggestedName={suggestedProjectName(lead.name, lead.scope)}
              />
            )}
            {!isLost && !lead.projectSlug && (
              <form action={markLost}>
                <button
                  type="submit"
                  className="rounded-md border border-rule bg-card px-2.5 py-1 text-[12px] font-semibold text-ink-3 hover:bg-paper-2 hover:text-flag"
                >
                  Mark lost
                </button>
              </form>
            )}
            <DeleteLeadButton slug={slug} name={lead.name} />
          </div>
        </div>

        <LeadTabs panels={panels} />
      </div>
    </Shell>
  );
}
