import Link from "next/link";
import { notFound } from "next/navigation";
import { Phone, Mail, Sparkles } from "lucide-react";
import { Shell } from "@/components/shell/Shell";
import { AiBubble, Card, Chip, Avatar, Eyebrow, Field } from "@/components/ui";
import { LeadTabs } from "@/components/leads/LeadTabs";
import { getLead, STAGES, stageIndex, stageLabel } from "@/lib/leads";
import { advanceLeadStage } from "@/lib/actions/leads";

const VERDICT: Record<string, { label: string; kind: "money" | "flag" | "info" }> = {
  go: { label: "GO", kind: "money" },
  hold: { label: "HOLD", kind: "info" },
  pass: { label: "PASS", kind: "flag" },
};

export default async function LeadDetailPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const lead = await getLead(slug);
  if (!lead) notFound();

  const verdict = VERDICT[lead.triage.verdict];
  const currentStageIdx = stageIndex(lead.stage);
  const nextStage = STAGES[currentStageIdx + 1];

  async function moveToNextStage() {
    "use server";
    await advanceLeadStage(slug);
  }

  const overview = (
    <div className="grid grid-cols-1 gap-4 lg:grid-cols-[1fr_320px]">
      {/* Main column */}
      <div className="flex flex-col gap-3.5">
        <AiBubble
          actions={
            <>
              <button className="rounded-md bg-ai px-2.5 py-1 text-[12px] font-semibold text-white hover:bg-ai-2">
                Run lead-triage skill again
              </button>
              <button className="rounded-md border border-rule px-2.5 py-1 text-[12px] font-semibold text-ink-3 hover:bg-paper-2 hover:text-ink-2">
                See reasoning
              </button>
            </>
          }
        >
          <div className="mb-1.5 font-serif text-[13.5px] font-semibold text-ai-2">
            Triage — Claude scored this lead {verdict.label}
          </div>
          <div>{lead.triage.rationale}</div>
        </AiBubble>

        <Card className="p-3.5">
          <h3 className="mb-2.5 font-serif text-[16px] font-semibold text-ink">
            5-Question intake
          </h3>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {lead.intake.map((f) => (
              <Field key={f.label} label={f.label} value={f.value} />
            ))}
          </div>
        </Card>

        {lead.estimate && (
          <Card className="p-3.5">
            <div className="flex items-center gap-2">
              <h3 className="flex-1 font-serif text-[16px] font-semibold text-ink">
                Phase 1 rough estimate
              </h3>
              <Chip kind="ai">Generated by Claude</Chip>
              <Chip kind="ghost">{lead.estimate.sentLabel}</Chip>
            </div>
            <div className="mt-2.5 flex flex-col">
              {lead.estimate.lines.map((line, i) => (
                <div
                  key={line.label}
                  className={`flex items-center py-1 ${i ? "border-t border-dashed border-rule-soft" : ""}`}
                >
                  <span className="flex-1 text-[13px] text-ink-2">{line.label}</span>
                  <span className="font-mono text-[12px] text-ink-2">{line.value}</span>
                </div>
              ))}
              <div className="mt-1.5 flex items-center border-t-2 border-ink-2 pt-2">
                <span className="flex-1 font-serif text-[16px] font-semibold text-ink">
                  Rough total
                </span>
                <span className="font-mono text-[16px] font-semibold text-accent-2">
                  {lead.estimate.total}
                </span>
              </div>
            </div>
          </Card>
        )}
      </div>

      {/* Sidebar */}
      <div className="flex flex-col gap-3">
        <Card kind="tan" className="p-3">
          <Eyebrow muted>Pipeline stage</Eyebrow>
          <div className="mt-2 flex flex-col gap-1.5">
            {STAGES.map((s, i) => {
              const done = i < currentStageIdx;
              const current = i === currentStageIdx;
              return (
                <div key={s.key} className="flex items-center gap-2">
                  <span
                    className={[
                      "size-3.5 flex-none rounded-[3px] border",
                      current
                        ? "border-accent bg-accent"
                        : done
                          ? "border-accent-2 bg-accent-2"
                          : "border-ink-4",
                    ].join(" ")}
                  />
                  <span className="w-3 font-mono text-[9px] text-ink-3">{i + 1}</span>
                  <span className={`flex-1 text-[13px] ${done || current ? "text-ink" : "text-ink-3"}`}>
                    {s.label}
                  </span>
                  {current && <Chip kind="accent">Here</Chip>}
                </div>
              );
            })}
          </div>
        </Card>

        <Card className="p-3">
          <Eyebrow muted>Cadence · SLA</Eyebrow>
          <div className="mt-2 flex flex-col gap-2">
            {lead.cadence.map((c) => (
              <div key={c.label} className="flex items-center gap-2">
                <span className="flex-1 text-[12px] text-ink-2">{c.label}</span>
                {c.chip ? (
                  <Chip kind={c.chip}>{c.value}</Chip>
                ) : (
                  <span className="font-mono text-[11px] text-ink-3">{c.value}</span>
                )}
              </div>
            ))}
          </div>
        </Card>

        {lead.photosCount > 0 && (
          <Card className="p-3">
            <Eyebrow muted>Photos · {lead.photosCount}</Eyebrow>
            <div className="mt-2 grid grid-cols-3 gap-1">
              {Array.from({ length: lead.photosCount }).map((_, i) => (
                <div
                  key={i}
                  className="aspect-square rounded-[3px] border border-rule bg-paper-3"
                />
              ))}
            </div>
          </Card>
        )}
      </div>
    </div>
  );

  return (
    <Shell breadcrumb={`LEADS › ${lead.name.toUpperCase()}`}>
      <div className="mx-auto max-w-[1100px] px-7 py-6">
        <Link href="/leads" className="text-[11px] text-ink-3 hover:text-ink-2">
          ← All leads
        </Link>

        {/* Header */}
        <div className="mt-2 flex flex-wrap items-start gap-4">
          <Avatar initials={lead.initials} kind="accent" size="lg" />
          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-1.5">
              <Chip kind="ghost">Source: {lead.source}</Chip>
              <Chip kind="ghost">
                Stage {currentStageIdx + 1} of 6
              </Chip>
            </div>
            <h1 className="mt-1.5 font-serif text-[30px] font-medium leading-none tracking-tight text-accent-2">
              {lead.name}
            </h1>
            <div className="mt-1.5 text-[11px] text-ink-3">{lead.address} · {lead.loggedLabel}</div>
          </div>
          <div className="flex items-center gap-1.5">
            <button className="inline-flex items-center gap-1 rounded-md border border-rule bg-card px-2.5 py-1 text-[12px] font-semibold text-ink hover:bg-paper-2">
              <Phone className="size-3" strokeWidth={1.5} />
              Call
            </button>
            <button className="inline-flex items-center gap-1 rounded-md border border-rule bg-card px-2.5 py-1 text-[12px] font-semibold text-ink hover:bg-paper-2">
              <Mail className="size-3" strokeWidth={1.5} />
              Email
            </button>
            <Link
              href="/ai"
              className="inline-flex items-center gap-1 rounded-md border border-ai bg-ai px-2.5 py-1 text-[12px] font-semibold text-white hover:bg-ai-2"
            >
              <Sparkles className="size-3" strokeWidth={1.5} />
              Ask Claude
            </Link>
            {nextStage ? (
              <form action={moveToNextStage}>
                <button
                  type="submit"
                  className="rounded-md border border-ink bg-ink px-2.5 py-1 text-[12px] font-semibold text-paper hover:bg-[#232a1e]"
                >
                  Move to {nextStage.label}
                </button>
              </form>
            ) : (
              <span className="rounded-md border border-rule bg-paper-2 px-2.5 py-1 text-[12px] font-semibold text-ink-3">
                Signed ✓
              </span>
            )}
          </div>
        </div>

        <LeadTabs overview={overview} />
      </div>
    </Shell>
  );
}
